# Generated by Django 2.2 on 2020-12-07 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOMERAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcustomer',
            name='customer_displya_name',
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='customer_display_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customer_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
