# Generated by Django 2.2 on 2020-12-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOMERAPP', '0003_auto_20201207_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='customer_email',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
